export * from "./appointment";
export * from "./auth";
export * from "./doctor";
export * from "./doctor-speciality";
export * from "./general";
export * from "./hours-of-work";
export * from "./language";
export * from "./patient";
export * from "./polyclinic";
